[package]
name = "prezl"
version = "0.1.0-beta.3"
description = "Staged code presentation environment"
authors = ["Matt Brailsford"]
edition = "2021"

[lib]
name = "prezl_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-deep-link = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[target."cfg(any(target_os = \"macos\", windows, target_os = \"linux\"))".dependencies]
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
